/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Users {
  createdAt: string;
  deletedAt: string | null;
  fullName: string | null;
  id: string | null;
  password: string;
  role: string;
  updatedAt: string;
  username: string;
}

export interface DB {
  users: Users;
}
