/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['categoryImage', 'categoryName', 'createdAt', 'id', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column()
  declare categoryImage: string | null
  @column()
  declare categoryName: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderSchema extends BaseModel {
  static $columns = ['createdAt', 'discount', 'id', 'items', 'note', 'orderId', 'paymentMethod', 'status', 'updatedAt', 'userId'] as const
  $columns = OrderSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare discount: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare items: any | null
  @column()
  declare note: string | null
  @column()
  declare orderId: string | null
  @column()
  declare paymentMethod: string | null
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class ProductSchema extends BaseModel {
  static $columns = ['barcode', 'barcodeImage', 'categoryId', 'createdAt', 'description', 'id', 'price', 'productCode', 'productImage', 'productName', 'quantity', 'updatedAt'] as const
  $columns = ProductSchema.$columns
  @column()
  declare barcode: string | null
  @column()
  declare barcodeImage: string | null
  @column()
  declare categoryId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare price: number
  @column()
  declare productCode: string
  @column()
  declare productImage: string | null
  @column()
  declare productName: string
  @column()
  declare quantity: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RoleAbilitySchema extends BaseModel {
  static $columns = ['abilityId', 'roleId'] as const
  $columns = RoleAbilitySchema.$columns
  @column()
  declare abilityId: string | null
  @column()
  declare roleId: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'fullName', 'id', 'password', 'role', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare username: string
}
