/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CategorySchema extends BaseModel {
  static $columns = ['categoryName', 'createdAt', 'id', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column()
  declare categoryName: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderSchema extends BaseModel {
  static $columns = ['createdAt', 'discount', 'id', 'items', 'note', 'paymentMethod', 'status', 'updatedAt', 'userId'] as const
  $columns = OrderSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare discount: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare items: any | null
  @column()
  declare note: string | null
  @column()
  declare paymentMethod: string | null
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class ProductSchema extends BaseModel {
  static $columns = ['barcode', 'barcodeImage', 'categoryId', 'createdAt', 'description', 'id', 'price', 'productCode', 'productImage', 'productName', 'quantity', 'updatedAt'] as const
  $columns = ProductSchema.$columns
  @column()
  declare barcode: string | null
  @column()
  declare barcodeImage: string | null
  @column()
  declare categoryId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare price: number
  @column()
  declare productCode: string
  @column()
  declare productImage: string | null
  @column()
  declare productName: string
  @column()
  declare quantity: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
