/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Orders {
  createdAt: string;
  discount: string | null;
  id: string | null;
  items: string | null;
  note: string | null;
  orderId: string | null;
  paymentMethod: string | null;
  status: Generated<string | null>;
  updatedAt: string;
  userId: string;
}

export interface DB {
  orders: Orders;
}
