/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Categories {
  categoryName: string;
  createdAt: string | null;
  id: string | null;
  updatedAt: string | null;
}

export interface Products {
  barcode: string | null;
  barcodeImage: string | null;
  categoryId: string | null;
  createdAt: string | null;
  description: string | null;
  id: string | null;
  price: number;
  productCode: string;
  productImage: string | null;
  productName: string;
  quantity: number | null;
  updatedAt: string | null;
}

export interface DB {
  categories: Categories;
  products: Products;
}
